### ISSUE TITLE
LinkTo doesn't generate href

### ISSUE THREAD

**Issue by NicholasJohn16** [storybookjs/ember-cli-storybook#14]
I've created a few components that use LinkTo, but I can't get the href attribute to generate. I'm using the preview version of Ember Octant with angle bracket components.

```js
// actor-name.hbs
<h5 class="actor-name">
    <LinkTo @route='people.person' @model={{this.args.actor}} class="actor-link" >
      {{this.actorName}}
    </LinkTo>
</h5>
```

```html
<!-- generated mark-up -->
<h5 class="actor-name">
    <a id="ember209" class="ember-view actor-link">
      Actor Name
    </a>
</h5>
```

I'm not getting any errors and the component works perfectly in the Ember app, just not in Storybook. I've tried passing in an object with an id property and an id number, but neither seem to work, even though both work in the app. Is there something I can do to get it to work properly?

**Comment by backspace** [comment]
I believe something similar is affecting me too; I have a [table component with sortable columns](https://deploy-preview-6507--nomad-storybook.netlify.com/?path=/story/components-table--sortable-columns), but clicking to change the sort doesn’t work. (It does initially make the iframe take over the page, but then, clicking does nothing.)

My theory is that this is happening because there’s no router in the Ember that’s running within the iframe. That could be a big problem for the application I’m working to migrate to Storybook 😳 

I’ll look further into this this week.

**Comment by backspace** [comment]
I got around this with some contained ugliness, thanks to a suggestion by @meirish. You can see the commit [here](https://github.com/hashicorp/nomad/pull/6507/commits/58b975824e72d03c180d219b627b34e622cb9611). The important code is this function:

```
function injectRoutedController(controllerClass) {
  return on('init', function() {
    const container = getOwner(this);
    container.register('controller:storybook', controllerClass);

    const routerFactory = container.factoryFor('router:main');
    routerFactory.class.map(function() {
      this.route('storybook');
    });

    const router = container.lookup('router:main');
    router.initialURL = 'storybook';
    router.startRouting(true);

    this.set('controller', container.lookup('controller:storybook'));
  });
}
```

It turns on routing, defines a `storybook` route, registers a `storybook` controller whose definition you pass in, and attaches it as `controller` on the “anonymous” Storybook component that provides `context`.

In the story for a paginated table, I use it like this:

```
    context: {
      injectRoutedController: injectRoutedController(
        Controller.extend({
          queryParams: ['currentPage'],
          currentPage: 1,
        })
      ),
      longList,
    },
```

The template refers to `controller.currentPage`.

Some caveats:

* `startRouting` is a [private interface](https://github.com/emberjs/ember.js/blob/26b3360d110dad94ed5b2d2837fbfde7fcfedb79/packages/%40ember/-internals/routing/lib/system/router.ts#L392) so who knows how long it’ll be around
* the `controller` property on the context isn’t defined immediately

It’s a bit unwieldy but it works at least! Maybe we can figure out a way to build this into the addon.

In your case, @NicholasJohn16, it looks like you wouldn’t need the controller, just the `startRouting` part. If your application renders anything by default on the application route, that could pose a problem; defining a new route worked in my case but that’s because the application template is empty-ish 🤔

**Comment by gabrielcsapo** [comment]
Thank you for the super helpful example and explanation @backspace .
